# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Photos

User.delete_all
Vphoto.delete_all
Tphoto.delete_all
Theme.delete_all
Vacation.delete_all

# Creating User
User.create(email: "admin@test.com", password: "secret")

# Themes Photos
tphoto1 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555974/EchtVakantie/Special___treehouse.jpg")
tphoto2 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555994/EchtVakantie/Nature2.jpg")
tphoto3 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555972/EchtVakantie/Camping.jpg")
tphoto4 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555999/EchtVakantie/Romance.jpg")
tphoto5 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555983/EchtVakantie/Historic2.jpg")
tphoto6 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555983/EchtVakantie/Food.jpg")
tphoto7 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555961/EchtVakantie/Farm_life.jpg")
tphoto8 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555971/EchtVakantie/Luxury.jpg")
tphoto9 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477555983/EchtVakantie/Take_a_ride.jpg")

# Themes
theme1 = Theme.new(name: "In de Bomen", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto1.theme = theme1
theme1.tphotos << tphoto1
theme1.save!
theme2 = Theme.new(name: "In de Natuur ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto2.theme = theme2
theme2.tphotos << tphoto2
theme2.save!
theme3 = Theme.new(name: "Camping", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto3.theme = theme3
theme3.tphotos << tphoto3
theme3.save!
theme4 = Theme.new(name: "Romantisch", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto4.theme = theme4
theme4.tphotos << tphoto4
theme4.save!
theme5 = Theme.new(name: "Historie", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto5.theme = theme5
theme5.tphotos << tphoto5
theme5.save!
theme6 = Theme.new(name: "Lekker", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto6.theme = theme6
theme6.tphotos << tphoto6
theme6.save!
theme7 = Theme.new(name: "Boerenleven", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto7.theme = theme7
theme7.tphotos << tphoto7
theme7.save!
theme8 = Theme.new(name: "Luxe", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto8.theme = theme8
theme8.tphotos << tphoto8
theme8.save!
theme9 = Theme.new(name: "Toeren", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto9.theme = theme9
theme9.tphotos << tphoto9
theme9.save!

#Vacations

#for Theme Nature
slapenBos = Vacation.create!(title: "Slapen in het Bos", address: "Benedelangs 35", country: "Nederland", region: "Midden Nederland", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
hihahut = Vacation.create!(title: "Hihahut", address: "Benedelangs 35", country: "Nederland", region: "Midden Nederland", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
ecolodge = Vacation.create!(title: "Ecolodge", address: "Benedelangs 35", country: "Nederland", region: "Zuid Holland", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
beekhuizen = Vacation.create!(title: "Buitenplaats Beekhuizen", address: "Benedelangs 35", country: "Nederland", region: "Noord Holland", price: "Prijzig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
boisBrule = Vacation.create!(title: "Bois Brule", address: "Benedelangs 35", country: "Belgie", region: "Zuid Belgie", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# for Theme SleepInTrees
treehotel = Vacation.create!(title: "Treehotel", address: "Benedelangs 35", country: "Zweden", region: "Noord Zweden", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme1], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
treeInn = Vacation.create!(title: "Tree Inn", address: "Benedelangs 35", country: "Duitsland", region: "Noord Duitsland", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme1], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
boomhut = Vacation.create!(title: "Boomhut", address: "Benedelangs 35", country: "Nederland", region: "Noord Holland", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme1], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
vogel = Vacation.create!(title: "De Vreemde Vogel", address: "Benedelangs 35", country: "Nederland", region: "Zuid Holland", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme1], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# for Theme Camping
simplyCanvas = Vacation.create!(title: "Simply Canvas", address: "Benedelangs 35", country: "Frankrijk", region: "Zuid Frankrijk", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
verborgen = Vacation.create!(title: "Verborgen Verblijf", address: "Benedelangs 35", country: "Nederland", region: "Noord Holland", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
lesOrmes = Vacation.create!(title: "Camping Les Ormes", address: "Benedelangs 35", country: "Frankrijk", region: "Zuid Frankrijk", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
daniel = Vacation.create!(title: "Daniel - Smart Luxury", address: "Benedelangs 35", country: "Oostenrijk", region: "Wenen", price: "Prijzig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
silver = Vacation.create!(title: "Camp Silver", address: "Benedelangs 35", country: "Nederland", region: "Noord Holland", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# for Theme Romantisch
nicolle = Vacation.create!(title: "Nicolle Tower", address: "Benedelangs 35", country: "Jersey", region: "St Clement", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme4], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
shelter7 = Vacation.create!(title: "Shelter7", address: "Benedelangs 35", country: "Belgie", region: "Gent", price: "Prijzig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme4], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# for Theme Historie
hougoumont = Vacation.create!(title: "Hougoumont", address: "Benedelangs 35", country: "Belgie", region: "Waterloo", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme5], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
cawood = Vacation.create!(title: "Cawood Castle", address: "Benedelangs 35", country: "Engeland", region: "North Yorkshire", price: "Prijzig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme5], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# for Theme Lekker
deKopvanLand = Vacation.create!(title: "de Kop van ‘t Land", address: "Benedelangs 35", country: "Nederland", region: "Zuid Holland", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme6], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
geversduin = Vacation.create!(title: "Geversduin", address: "Benedelangs 35", country: "Nederland", region: "Noord Holland", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme6], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
wijnstaete = Vacation.create!(title: "Wijnstaete", address: "Benedelangs 35", country: "Nederland", region: "Noord Holland", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme6], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# for Theme Boerenleven
ferme = Vacation.create!(title: "La Ferme du Moncel", address: "Benedelangs 35", country: "Frankrijk", region: "Noord Frankrijk", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme7], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
hayema = Vacation.create!(title: "Hayema Heerd", address: "Benedelangs 35", country: "Nederland", region: "Noord Holland", price: "Voordelig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme7], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# for Theme Luxe
cowleymanor = Vacation.create!(title: "Cowley Manor", address: "Benedelangs 35", country: "Engeland", region: "Gloucestershire", price: "Prijzig", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme8], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# for Theme Toeren
buske = Vacation.create!(title: "It Blauwe Buske", address: "Benedelangs 35", country: "Nederland", region: "Friesland", price: "Gemiddeld", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: "true", themes: [theme9], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")

# Photos for Vacations
Vphoto.create!(vacation: slapenBos, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/Nature_-_SlapenInHetBos_-_1.jpg")
Vphoto.create!(vacation: slapenBos, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/Nature_-_SlapenInHetBos_-_2.jpg")
Vphoto.create!(vacation: slapenBos, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/Nature_-_SlapenInHetBos_-_3.jpg")

Vphoto.create!(vacation: hihahut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/Nature_-_Hihahut_-_1.jpg")
Vphoto.create!(vacation: hihahut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/Nature_-_Hihahut_-_2.jpg")
Vphoto.create!(vacation: hihahut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/Nature_-_Hihahut_-_3.jpg")

Vphoto.create!(vacation: ecolodge, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_EchoLodge_-_1.jpg")
Vphoto.create!(vacation: ecolodge, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_Echolodge_-_2.jpg")
Vphoto.create!(vacation: ecolodge, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_Ecolodge_-_3.jpg")

Vphoto.create!(vacation: beekhuizen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_BuitenPlaats_-_1.jpg")
Vphoto.create!(vacation: beekhuizen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_BuitenPlaats_-_2.jpg")
Vphoto.create!(vacation: beekhuizen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_BuitenPlaats_-_3.jpg")

Vphoto.create!(vacation: boisBrule, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556084/EchtVakantie/Nature_-_BoisBrule_-_1.jpg")
Vphoto.create!(vacation: boisBrule, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Nature_-_BousBrule_-_2.jpg")
Vphoto.create!(vacation: boisBrule, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Nature_-_BoisBrule_-_3.jpg")

Vphoto.create!(vacation: treehotel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/SleepInTrees_-_TreeHotel_-_1.jpg")
Vphoto.create!(vacation: treehotel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/SleepInTrees_-_TreeHotel_-_2.jpg")
Vphoto.create!(vacation: treehotel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/SleepInTrees_-_TreeHotel_-_3.jpg")

Vphoto.create!(vacation: treeInn, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_TreeInn_-_1.jpg")
Vphoto.create!(vacation: treeInn, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_TreeInn_-_2.jpg")
Vphoto.create!(vacation: treeInn, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_TreeInn_-_3.jpg")

Vphoto.create!(vacation: boomhut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/SleepInTrees_-_Boomhut_-_1.jpg")
Vphoto.create!(vacation: boomhut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/SleepInTrees_-_Boomhut_-_2.jpg")
Vphoto.create!(vacation: boomhut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/SleepInTrees_-_Boomhut_-_3.jpg")

Vphoto.create!(vacation: vogel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_VreemdeVogel_-_1.jpg")
Vphoto.create!(vacation: vogel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_VreemdeVogel_-_2.jpg")
Vphoto.create!(vacation: vogel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_VreemdeVogel_-_3.jpg")

Vphoto.create!(vacation: simplyCanvas, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556084/EchtVakantie/Camping_-_Simply_Canvas_-_1.jpg")
Vphoto.create!(vacation: simplyCanvas, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556084/EchtVakantie/Camping_-_Simply_Canvas_-_2.jpg")
Vphoto.create!(vacation: simplyCanvas, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556084/EchtVakantie/Camping_-_Simply_Canvas.jpg")

Vphoto.create!(vacation: verborgen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Camping_-_Verborgen_-_1.jpg")
Vphoto.create!(vacation: verborgen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Camping_-_Verborgen_-_2.jpg")
Vphoto.create!(vacation: verborgen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Camping_-_Verborgen_-_3.jpg")

Vphoto.create!(vacation: lesOrmes, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_LesOrmes_-_1.jpg")
Vphoto.create!(vacation: lesOrmes, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_LesOrmes_-_2.jpg")
Vphoto.create!(vacation: lesOrmes, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_LesOrmes_-_3.jpg")

Vphoto.create!(vacation: daniel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_Daniel_-_1.jpg")
Vphoto.create!(vacation: daniel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_Daniel_-_2.jpg")
Vphoto.create!(vacation: daniel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_Daniel_-_3.jpg")

Vphoto.create!(vacation: silver, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477558630/EchtVakantie/Camping_-_Silver_-_1.jpg")
Vphoto.create!(vacation: silver, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477558630/EchtVakantie/Camping_-_Silver_-_2.jpg")
Vphoto.create!(vacation: silver, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477558630/EchtVakantie/Camping_-_Silver_-_3.jpg")

Vphoto.create!(vacation: nicolle, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477643061/nicolle_tower-romantic_wyttrr.jpg")
Vphoto.create!(vacation: shelter7, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477643065/Shelter7_romantic_qnsav3.jpg")

Vphoto.create!(vacation: hougoumont, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477643459/hougoumont-waterloo_echt_historisch_l0hasb.jpg")
Vphoto.create!(vacation: cawood, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477643469/cawood-castle-1_echt_historisch_lmkj2o.jpg")

Vphoto.create!(vacation: deKopvanLand, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644063/EchtVakantie/Kop_van_het_land___echt_lekker.jpg")
Vphoto.create!(vacation: geversduin, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644057/EchtVakantie/geversduin_groentehuisje_echt_lekker.jpg")
Vphoto.create!(vacation: wijnstaete, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644216/EchtVakantie/Wijnstaete_echt_lekker.jpg")

Vphoto.create!(vacation: ferme, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644687/EchtVakantie/ferme-du-moncel_Echt_boerenleven.jpg")
Vphoto.create!(vacation: hayema, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644684/EchtVakantie/hayemaheerd_echt_boerenleven.jpg")

Vphoto.create!(vacation: cowleymanor, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477646536/EchtVakantie/Cowley_manor_echt_luxe.jpg")

Vphoto.create!(vacation: buske, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477646904/EchtVakantie/blauwebusketours_echt_toeren.jpg")
