# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# Photos

User.delete_all
Vphoto.delete_all
Tphoto.delete_all
Theme.delete_all
Vacation.delete_all

# Creating User
User.create(email: ENV['EMAIL_USER'] || "admin@test.com", password: ENV['EMAIL_PASSWD'] || "secret")

# Themes Photos
tphoto1 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/c_scale,q_auto:low,w_1339/v1477650346/EchtVakantie/theme/Special___treehouse.jpg")
tphoto2 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/c_scale,q_auto:low,w_1325/v1477650352/EchtVakantie/theme/Nature2.jpg")
tphoto3 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/c_scale,q_auto:low,w_1327/v1477650344/EchtVakantie/theme/Camping.jpg")
tphoto4 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/c_scale,q_auto:low,w_1379/v1477650354/EchtVakantie/theme/Romance.jpg")
tphoto5 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/c_scale,q_auto:low,w_1407/v1477650344/EchtVakantie/theme/Historic2.jpg")
tphoto6 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/c_scale,q_auto:low,w_1397/v1477650349/EchtVakantie/theme/Food.jpg")
tphoto7 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/q_auto:low/v1477650341/EchtVakantie/theme/Farm_life.jpg")
tphoto8 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/c_scale,q_auto:low,w_1359/v1477650344/EchtVakantie/theme/Luxury.jpg")
tphoto9 = Tphoto.new(remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/c_scale,q_auto:low,w_1354/v1477650352/EchtVakantie/theme/Take_a_ride.jpg")

# Themes
theme1 = Theme.new(name: "Special: Boomhut", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto1.theme = theme1
theme1.tphotos << tphoto1
theme1.save!
theme2 = Theme.new(name: "In de Natuur ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto2.theme = theme2
theme2.tphotos << tphoto2
theme2.save!
theme3 = Theme.new(name: "Glamping", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto3.theme = theme3
theme3.tphotos << tphoto3
theme3.save!
theme4 = Theme.new(name: "Romantisch", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto4.theme = theme4
theme4.tphotos << tphoto4
theme4.save!
theme5 = Theme.new(name: "Echt Oud", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto5.theme = theme5
theme5.tphotos << tphoto5
theme5.save!
theme6 = Theme.new(name: "Lekker Eten", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto6.theme = theme6
theme6.tphotos << tphoto6
theme6.save!
theme7 = Theme.new(name: "Kids mee", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto7.theme = theme7
theme7.tphotos << tphoto7
theme7.save!
theme8 = Theme.new(name: "Echt Luxe", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto8.theme = theme8
theme8.tphotos << tphoto8
theme8.save!
theme9 = Theme.new(name: "Toeren & Varen", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", style: "nil")
tphoto9.theme = theme9
theme9.tphotos << tphoto9
theme9.save!

#Vacations

#for Theme Nature
slapenBos = Vacation.create!(title: "Slapen in het Bos", address: "Asselsestraat 405, Apeldoorn", country: "Nederland", region: "Midden Nederland", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.slapeninhetbos.nl', booking: 'www.slapeninhetbos.nl/reserveren')
hihahut = Vacation.create!(title: "Hihahut", address: "Langeweg 16, Roelofarendsveen", country: "Nederland", region: "Midden Nederland", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.hihahut.nl', booking: 'www.hihahut.nl/hihahut-avontuur')
ecolodge = Vacation.create!(title: "Ecolodge", address: "Baanhoekweg 25, Dordrecht", country: "Nederland", region: "Zuid Holland", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.slapenopdeecolodge.nl/nl/home', booking: 'www.slapenopdeecolodge.nl/nl/direct-boeken')
beekhuizen = Vacation.create!(title: "Buitenplaats Beekhuizen", address: "Bovenallee 1, Velp", country: "Nederland", region: "Gelderland", price: "hoog", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.buitenplaatsbeekhuizen.nl', booking: 'www.buitenplaatsbeekhuizen.nl')
boisBrule = Vacation.create!(title: "Bois Brule", address: "Derrière les Thiers 3a, Trou de Bra", country: "Belgie", region: "Zuid Belgie", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme2], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.boisbrule.be/en/', booking: 'www.boisbrule.be/en/')

# for Theme SleepInTrees
treehotel = Vacation.create!(title: "Treehotel", address: "Edeforsväg 2, Harads", country: "Zweden", region: "Noord Zweden", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme1], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.treehotel.se/en/', booking: 'www.treehotel.se/en/')
treeInn = Vacation.create!(title: "Tree Inn", address: "Kasernenstraße 2, Dörverden", country: "Duitsland", region: "Noord Duitsland", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme1], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.tree-inn.de', booking: 'www.tree-inn.de')
boomhut = Vacation.create!(title: "Boomhut", address: "Badweg 1, L'stad", country: "Nederland", region: "Noord Holland", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme1], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.boomhutovernachtingen.nl', booking: 'www.secure.maxengine.eu/?hotel_id=3857&template=boomhutovernachtingen')
vogel = Vacation.create!(title: "De Vreemde Vogel", address: "van Baerlesstraat 252, Vlaardingen", country: "Nederland", region: "Zuid Holland", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme1], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.devreemdevogel.nl', booking: 'www.devreemdevogel.nl')

# for Theme Camping
simplyCanvas = Vacation.create!(title: "Simply Canvas", address: "Bonac, Saint Jean de Duras", country: "Frankrijk", region: "Zuid Frankrijk", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.simplycanvas.eu/en/', booking: 'www.simplycanvas.eu/en/about-simply-canvas/simply-bed-and-breakfast-availability.html')
verborgen = Vacation.create!(title: "Verborgen Verblijf", address: "Almere", country: "Nederland", region: "Noord Holland", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.verborgenverblijf.nl', booking: 'www.verborgenverblijf.nl')
lesOrmes = Vacation.create!(title: "Camping Les Ormes", address: "Lieu Dit Fauquié Haut, Saint-Étienne-de-Villeréal", country: "Frankrijk", region: "Zuid Frankrijk", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.campinglesormes.fr', booking: 'www.campinglesormes.fr/reservation-camping-15.html')
daniel = Vacation.create!(title: "Daniel - Smart Luxury", address: "Landstraßer Gürtel 5, Vienna", country: "Oostenrijk", region: "Wenen", price: "hoog", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.hoteldaniel.com/en/', booking: 'www.hoteldaniel.com/en/')
silver = Vacation.create!(title: "Camp Silver", address: "Eendenkooiweg 2, Oosterend", country: "Nederland", region: "Noord Holland", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme3], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.campsilver.nl/en/', booking: 'www.campsilver.nl/en/reservations/')

# for Theme Romantisch
nicolle = Vacation.create!(title: "Nicolle Tower", address: "St Clement, Jersey", country: "Jersey", region: "St Clement", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme4], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.landmarktrust.org.uk/search-and-book/properties/nicolle-tower-9638', booking: 'www.landmarktrust.org.uk/search-and-book/properties/nicolle-tower-9638')
shelter7 = Vacation.create!(title: "Shelter7", address: "Bennesteeg 7, Gent", country: "Belgie", region: "Gent", price: "hoog", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme4], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.shelter7.be', booking: 'www.shelter7.be')

# for Theme Historie
hougoumont = Vacation.create!(title: "Hougoumont", address: "Hougoumont, Waterloo, Belgium", country: "Belgie", region: "Waterloo", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme5], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.landmarktrust.org.uk/search-and-book/properties/hougoumont-waterloo-24855', booking: 'www.landmarktrust.org.uk/search-and-book/properties/hougoumont-waterloo-24855')
cawood = Vacation.create!(title: "Cawood Castle", address: "Cawood, North Yorkshire", country: "Engeland", region: "North Yorkshire", price: "hoog", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme5], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.landmarktrust.org.uk/search-and-book/properties/cawood-castle-6033?gclid=Cj0KEQiAvNrBBRDe3IOwzLn6_O4BEiQAmbK-DjF8F-X6CobJfBIe5pHlxgfLwQchQgQHPPJZg-_XLXAaAqze8P8HAQ', booking: 'www.landmarktrust.org.uk/search-and-book/properties/cawood-castle-6033?gclid=Cj0KEQiAvNrBBRDe3IOwzLn6_O4BEiQAmbK-DjF8F-X6CobJfBIe5pHlxgfLwQchQgQHPPJZg-_XLXAaAqze8P8HAQ')

# for Theme Lekker
deKopvanLand = Vacation.create!(title: "de Kop van ‘t Land", address: "Zeedijk 32, Dordrecht", country: "Nederland", region: "Zuid Holland", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme6], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.kopvanhetland.nl', booking: 'www.kopvanhetland.nl/reserveren/')
geversduin = Vacation.create!(title: "Geversduin", address: "Beverwijkerstraatweg 205, Castricum ", country: "Nederland", region: "Noord Holland", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme6], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.campinggeversduin.nl', booking: 'www.campinggeversduin.nl')
wijnstaete = Vacation.create!(title: "Wijnstaete", address: "Vilstersedijk 13, Lemelerveld", country: "Nederland", region: "Noord Holland", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme6], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.wijnstaete.nl', booking: 'www.wijnstaete.nl')

# for Theme Boerenleven
ferme = Vacation.create!(title: "La Ferme du Moncel", address: "Lower Normandy, Fay", country: "Frankrijk", region: "Noord Frankrijk", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme7], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.boerenbed.nl/locatie/la-ferme-du-moncel/', booking: 'www.boerenbed.nl/locatie/la-ferme-du-moncel/')
hayema = Vacation.create!(title: "Hayema Heerd", address: "Jensemaweg 3, Oldehove", country: "Nederland", region: "Noord Holland", price: "laag", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme7], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.hayemaheerd.com', booking: 'www.hayemaheerd.com')

# for Theme Luxe
cowleymanor = Vacation.create!(title: "Cowley Manor", address: "Cowley, Near Cheltenham", country: "Engeland", region: "Gloucestershire", price: "hoog", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme8], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.cowleymanor.com', booking: 'www.cowleymanor.com')

# for Theme Toeren
buske = Vacation.create!(title: "It Blauwe Buske", address: "Birstum 5, Nes ", country: "Nederland", region: "Friesland", price: "midden", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", show: true, themes: [theme9], review: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", more_info: 'www.itblauwebuske.nl', booking: 'www.itblauwebuske.nl')

# Photos for Vacations
Vphoto.create!(vacation: slapenBos, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/Nature_-_SlapenInHetBos_-_1.jpg")
Vphoto.create!(vacation: slapenBos, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/Nature_-_SlapenInHetBos_-_2.jpg")
Vphoto.create!(vacation: slapenBos, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/Nature_-_SlapenInHetBos_-_3.jpg")

Vphoto.create!(vacation: hihahut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/Nature_-_Hihahut_-_1.jpg")
Vphoto.create!(vacation: hihahut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/Nature_-_Hihahut_-_2.jpg")
Vphoto.create!(vacation: hihahut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/Nature_-_Hihahut_-_3.jpg")

Vphoto.create!(vacation: ecolodge, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_EchoLodge_-_1.jpg")
Vphoto.create!(vacation: ecolodge, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_Echolodge_-_2.jpg")
Vphoto.create!(vacation: ecolodge, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_Ecolodge_-_3.jpg")

Vphoto.create!(vacation: beekhuizen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_BuitenPlaats_-_1.jpg")
Vphoto.create!(vacation: beekhuizen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_BuitenPlaats_-_2.jpg")
Vphoto.create!(vacation: beekhuizen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556086/EchtVakantie/Nature_-_BuitenPlaats_-_3.jpg")

Vphoto.create!(vacation: boisBrule, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556084/EchtVakantie/Nature_-_BoisBrule_-_1.jpg")
Vphoto.create!(vacation: boisBrule, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Nature_-_BousBrule_-_2.jpg")
Vphoto.create!(vacation: boisBrule, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Nature_-_BoisBrule_-_3.jpg")

Vphoto.create!(vacation: treehotel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/SleepInTrees_-_TreeHotel_-_1.jpg")
Vphoto.create!(vacation: treehotel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/SleepInTrees_-_TreeHotel_-_2.jpg")
Vphoto.create!(vacation: treehotel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556089/EchtVakantie/SleepInTrees_-_TreeHotel_-_3.jpg")

Vphoto.create!(vacation: treeInn, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_TreeInn_-_1.jpg")
Vphoto.create!(vacation: treeInn, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_TreeInn_-_2.jpg")
Vphoto.create!(vacation: treeInn, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_TreeInn_-_3.jpg")

Vphoto.create!(vacation: boomhut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/SleepInTrees_-_Boomhut_-_1.jpg")
Vphoto.create!(vacation: boomhut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/SleepInTrees_-_Boomhut_-_2.jpg")
Vphoto.create!(vacation: boomhut, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556088/EchtVakantie/SleepInTrees_-_Boomhut_-_3.jpg")

Vphoto.create!(vacation: vogel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_VreemdeVogel_-_1.jpg")
Vphoto.create!(vacation: vogel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_VreemdeVogel_-_2.jpg")
Vphoto.create!(vacation: vogel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556090/EchtVakantie/SleepInTrees_-_VreemdeVogel_-_3.jpg")

Vphoto.create!(vacation: simplyCanvas, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556084/EchtVakantie/Camping_-_Simply_Canvas_-_1.jpg")
Vphoto.create!(vacation: simplyCanvas, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556084/EchtVakantie/Camping_-_Simply_Canvas_-_2.jpg")
Vphoto.create!(vacation: simplyCanvas, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556084/EchtVakantie/Camping_-_Simply_Canvas.jpg")

Vphoto.create!(vacation: verborgen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Camping_-_Verborgen_-_1.jpg")
Vphoto.create!(vacation: verborgen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Camping_-_Verborgen_-_2.jpg")
Vphoto.create!(vacation: verborgen, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556085/EchtVakantie/Camping_-_Verborgen_-_3.jpg")

Vphoto.create!(vacation: lesOrmes, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_LesOrmes_-_1.jpg")
Vphoto.create!(vacation: lesOrmes, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_LesOrmes_-_2.jpg")
Vphoto.create!(vacation: lesOrmes, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_LesOrmes_-_3.jpg")

Vphoto.create!(vacation: daniel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_Daniel_-_1.jpg")
Vphoto.create!(vacation: daniel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_Daniel_-_2.jpg")
Vphoto.create!(vacation: daniel, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477556083/EchtVakantie/Camping_-_Daniel_-_3.jpg")

Vphoto.create!(vacation: silver, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477558630/EchtVakantie/Camping_-_Silver_-_1.jpg")
Vphoto.create!(vacation: silver, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477558630/EchtVakantie/Camping_-_Silver_-_2.jpg")
Vphoto.create!(vacation: silver, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477558630/EchtVakantie/Camping_-_Silver_-_3.jpg")

Vphoto.create!(vacation: nicolle, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477643061/nicolle_tower-romantic_wyttrr.jpg")
Vphoto.create!(vacation: shelter7, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477643065/Shelter7_romantic_qnsav3.jpg")

Vphoto.create!(vacation: hougoumont, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477643459/hougoumont-waterloo_echt_historisch_l0hasb.jpg")
Vphoto.create!(vacation: cawood, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477643469/cawood-castle-1_echt_historisch_lmkj2o.jpg")

Vphoto.create!(vacation: deKopvanLand, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644063/EchtVakantie/Kop_van_het_land___echt_lekker.jpg")
Vphoto.create!(vacation: geversduin, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644057/EchtVakantie/geversduin_groentehuisje_echt_lekker.jpg")
Vphoto.create!(vacation: wijnstaete, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644216/EchtVakantie/Wijnstaete_echt_lekker.jpg")

Vphoto.create!(vacation: ferme, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644687/EchtVakantie/ferme-du-moncel_Echt_boerenleven.jpg")
Vphoto.create!(vacation: hayema, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477644684/EchtVakantie/hayemaheerd_echt_boerenleven.jpg")

Vphoto.create!(vacation: cowleymanor, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477646536/EchtVakantie/Cowley_manor_echt_luxe.jpg")

Vphoto.create!(vacation: buske, remote_image_url: "http://res.cloudinary.com/dfc7k24vb/image/upload/v1477646904/EchtVakantie/blauwebusketours_echt_toeren.jpg")
